### PR TITLE
Homestays

### PR DESCRIPTION
**Pull request by nathancday**
@matthew-e-thomas do you consider the new README and XLSX file ready to merge into Master?

To me it looks like we only want those last 2 commits, do you agree?

### CODE REVIEW

**Comment by matthew-e-thomas** [comment]
Yes, I think that's right

**Comment by nathancday** [comment]
So why did you merge all of them?

It's generally a good idea when you bring a feature branch back  into master to "Squash & Merge" instead of just merging "Merge". It's a drop down option on the web-UI and keeps the history clean so it's easy to see the changes in meaningful chunks.

**Comment by matthew-e-thomas** [comment]
I'm sorry, I didn't realize I was merging all of them, I saw a pull request and thought you wanted me to merge. Is there a way to undo it?

**Comment by nathancday** [comment]
It's not a big deal, and I wasn't explicit about it on Github, but I think
this is a perfect time to show off some of the advanced/real-world Git
usage. With Git all things are reversible, I'll leave 5 minutes to go over
it at the meeting on Thursday.

**Pull request merged**
